// PSI · PSB · PART IVA ASSESSOR TAB (Div 84–87 ITAA 1997, Part IVA ITAA 1936, PCG 2021/4)
// Everything is wrapped in a function so its names can't clash with other tabs.

(function(){
/* =========================================================
   TAX RATES — taken from the suite's shared TAX_DATA (shared/tax-data.js),
   so updating that file each year updates this tool too.
   TAX_DATA is keyed by the year the FY ends ("2027" = 2026-27); it is converted
   here to this tool's shape:
   { "2026-27": { label, ind:[[threshold,rate],...], coBase, coFull, top, superTax, div293Threshold } }
   ind brackets: rate applies to income ABOVE threshold up to the next.
   Medicare levy and offsets excluded (matches the PCG 2021/4 method).
========================================================= */
const RATES = {};
Object.keys(TAX_DATA).sort((a, b) => b - a).forEach(k => {
  const d = TAX_DATA[k];
  const fy = `${k - 1}-${String(k).slice(-2)}`;
  const bands = d.brackets.filter(b => b.rate > 0);
  const co = d.companyTax || { baseRate: 0.25, fullRate: 0.30 };
  RATES[fy] = {
    label: 'FY' + fy,
    ind: bands.map(b => [b.min, b.rate]),
    coBase: co.baseRate,
    coFull: co.fullRate,
    top: bands[bands.length - 1].rate,        // s99A trustee rate = top marginal rate
    superTax: 0.15,                           // contributions tax
    div293Threshold: d.div293Threshold
  };
});
const DEFAULT_FY = RATES["2025-26"] ? "2025-26" : Object.keys(RATES)[0];

const $ = s => document.querySelector('#psi-tool ' + s);
const $$ = s => Array.from(document.querySelectorAll('#psi-tool ' + s));
const num = v => { const n = parseFloat(String(v ?? '').replace(/[^0-9.\-]/g,'')); return isFinite(n) ? n : 0; };
const money = n => (n<0?'-':'') + '$' + Math.round(Math.abs(n)).toLocaleString('en-AU');
const pct = n => (isFinite(n) ? n.toFixed(2) : '0.00') + '%';
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let uid = 1;

/* =========================================================
   STATE
========================================================= */
function blankState(){
  return {
    client:{name:'', ipp:'', structure:'company', fy:DEFAULT_FY},
    answers:{psi:{}, psb:{}, iva:{}},
    gw1:{}, gw2:{},
    fin:{ coProfit:0, coRate:'coBase', franking:100, benchmark:0,
      ipp:{wages:0, super:0, div:0, other:0},
      parties:[],
      opts:{superInF1:true, contribTax:true, div293:true, useF3:false} }
  };
}
let S = blankState();

/* =========================================================
   FLOWCHARTS
========================================================= */
const OUTCOMES = {
  NOT_PSI:{tone:'green', title:'Not personal services income', text:'The PSI rules (Divs 84–87) do not apply, so the PSB tests are not needed. Still consider Part IVA and PCG 2021/4 for how firm profits are allocated.'},
  BUS_STRUCT:{tone:'green', title:'Not PSI – earned from a business structure', text:"With more employees than principals, the income is generated by the business structure (its staff, systems and goodwill) rather than mainly by the principals' personal efforts or skills. The PSI rules do not apply, so the PSB tests are not needed. Still consider Part IVA and PCG 2021/4 for how profits are allocated."},
  EMPLOYEE:{tone:'grey', title:'Employee income', text:'Salary or wages received as an employee are taxed to the individual directly and are outside the PSI attribution rules. PSB tests not required.'},
  PSI:{tone:'amber', title:'Income is PSI', text:'Proceed to the PSB tests in Step 2.'},
  PSB:{tone:'green', title:'Personal services business (self-assessed)', text:'The PSI attribution rules do not apply. Income can be retained in / distributed from the entity, subject to Part IVA (Step 3).'},
  DETERMINATION:{tone:'amber', title:'Seek a PSB determination from the ATO', text:'The client cannot self-assess as a PSB. Apply for a PSB determination (s87-60/87-65). Until one is issued, the PSI rules apply.'},
  PSI_APPLIES:{tone:'red', title:'PSI rules apply', text:'The PSI is attributed to the individual (s86-15). Entity deductions are limited (Div 85 / s86-60).'},
  IVA_NOT:{tone:'green', title:'Part IVA should not apply', text:'On the structure-check flowchart, the arrangement does not present the usual Part IVA indicators for PSI.'},
  IVA_MAY:{tone:'red', title:'Part IVA may apply', text:'Discuss with the client ways of reducing the Part IVA risk (e.g. increasing remuneration to the principal, paying out retained profits, restructuring distributions).'},
  IVA_PSI:{tone:'green', title:'PSI rules attribute income to the individual', text:'Because the PSI rules apply, the income is attributed to the principal worker. Part IVA should not generally be needed for the PSI itself.'},
  IVA_NA:{tone:'grey', title:'No interposed entity', text:'Income is earned directly by the individual, so there is no entity to split or retain income through. The Part IVA structure check, gateways and PCG 2021/4 scoring are not required.'}
};

const FLOWS = {
  psi:{ start:()=> 'p1', nodes:{
    p1:{ref:'s84-5 ITAA 1997', q:"Is the income mainly (more than 50%) a reward for an individual's personal efforts or skills?",
        hint:'It is not PSI where the income is mainly for supplying or selling goods, from granting a right to use property, or generated by income-producing assets or a business structure (e.g. a practice with substantial staff, goodwill and systems).',
        yes:'p2', no:'@NOT_PSI'},
    p2:{ref:'s84-5 / Div 86', q:"Is the income received by the individual as an employee (salary or wages from the payer)?",
        hint:'Answer "No" if the individual contracts directly or through a company, trust or partnership.',
        yes:'@EMPLOYEE', no:'bs'},
    bs:{ref:'s84-5 ITAA 1997 · business structure', q:"Does the business have more employees than principals?",
        hint:"Principals are the individuals whose personal efforts or skills generate the income (e.g. the directors, partners or owners doing the work). Where employees outnumber principals, the income is generated by the business structure rather than mainly by the principals' personal efforts.",
        yes:'@BUS_STRUCT', no:'@PSI'}
  }},
  psb:{ start:()=> 'r', nodes:{
    r:{ref:'s87-18 Results test', q:'Is at least 75% of the PSI for the year earned under arrangements that meet all three results-test conditions?',
       hint:'<ul><li>Paid for producing a result (not hourly/daily rates)</li><li>Required to supply the plant, equipment or tools needed to do the work</li><li>Liable for the cost of rectifying defects</li></ul>',
       yes:'@PSB', no:'e80'},
    e80:{ref:'s87-15 80% rule', q:'Does 80% or more of the PSI come from one client (and its associates)?',
       hint:'If yes, the client cannot self-assess under the other three tests — a PSB determination is needed.',
       yes:'any', no:'uc'},
    uc:{ref:'s87-20 Unrelated clients test', q:'Is PSI received from two or more unrelated clients, as a direct result of making offers or invitations to the public?',
       hint:'e.g. advertising, website, tendering. Clients must not be associates of each other or of the worker.', yes:'@PSB', no:'emp'},
    emp:{ref:'s87-25 Employment test', q:'Does the entity engage others (who are not associates) to perform at least 20% of the principal work by market value, or have an apprentice for at least half the year?',
       hint:'Associates can count only if the work they do is principal work of the business.', yes:'@PSB', no:'bp'},
    bp:{ref:'s87-30 Business premises test', q:'At all times during the year, does the entity have business premises that it uses mainly for the PSI activities, with exclusive use, physically separate from private premises and from the premises of clients and their associates?',
       hint:'All four conditions must be met for the whole period the business is conducted.', yes:'@PSB', no:'spec'},
    any:{ref:'s87-15 / s87-65', q:'Could they otherwise pass the unrelated clients, employment or business premises test?',
       hint:'If so, apply to the ATO for a PSB determination.', yes:'@DETERMINATION', no:'spec'},
    spec:{ref:'s87-60 / s87-65', q:'Are there special or unusual circumstances that prevented the entity from meeting one or more of the tests?',
       hint:'e.g. an unusual event such as illness, natural disaster, or the business being in its first year.', yes:'@DETERMINATION', no:'@PSI_APPLIES'}
  }},
  iva:{ start:()=>{
      if (S.client.structure === 'sole') return '@IVA_NA';
      const b = flowOutcome('psb');
      if (flowOutcome('psi') === 'PSI' && b === 'PSI_APPLIES') return '@IVA_PSI';
      return 'rel';
    }, nodes:{
    rel:{ref:'Part IVA ITAA 1936', q:'Is any of the income paid to a family member (other than a spouse in a genuine husband-and-wife partnership) or other related entity of the principal worker?',
       hint:'Includes wages, super, distributions or dividends to associates, family trusts or bucket companies.', yes:'reas', no:'ent'},
    reas:{ref:'Part IVA', q:'Is each amount reasonable remuneration for bona fide services actually performed?',
       hint:'Compare to what an arm\'s-length person would be paid for the same work. Tip: use the related-party rows in 3c to document hours and duties.', yes:'ent', no:'@IVA_MAY'},
    ent:{auto:true},
    hw:{ref:'TR 94/8', q:'Is the partnership a genuine husband-and-wife partnership?',
       hint:'Both spouses must genuinely carry on the business together, with the partnership income not being just the personal-exertion income of one spouse.', yes:'@IVA_NOT', no:'@IVA_MAY'},
    ret:{ref:'Part IVA', q:'Are any profits retained in the company or trust at 30 June?', hint:'', yes:'be', no:'@IVA_NOT'},
    be:{ref:'Part IVA', q:'Are BOTH of these met: (1) a legitimate attempt was made to break even by 30 June, and (2) any profits at 30 June are paid to the principal worker in the following year?',
       hint:'', yes:'@IVA_NOT', no:'@IVA_MAY'}
  }}
};

function resolveAuto(flow, id){
  if (flow==='iva' && id==='ent') return S.client.structure==='partnership' ? 'hw' : 'ret';
  return id;
}

function walk(flow){
  const F = FLOWS[flow]; const path = [];
  let id = F.start(); let guard=0;
  while (guard++ < 30){
    if (id.startsWith('@')) return {path, outcome:id.slice(1)};
    id = resolveAuto(flow, id);
    const n = F.nodes[id]; path.push(id);
    const a = S.answers[flow][id];
    if (a === undefined) return {path, outcome:null};
    id = a ? n.yes : n.no;
  }
  return {path, outcome:null};
}
function flowOutcome(flow){
  if (flow==='psb'){
    const p = walk('psi').outcome;
    if (p !== 'PSI') return p ? 'SKIP' : null;
  }
  return walk(flow).outcome;
}

function renderFlow(flow){
  const el = $('#flow-' + flow);
  if (flow==='psb'){
    const p = walk('psi').outcome;
    if (!p){ el.innerHTML = '<div class="info">Complete Step 1 first.</div>'; return; }
    if (p !== 'PSI'){ el.innerHTML = outcomeHTML({tone:'grey', title:'PSB tests not required', text:'Step 1 found the income is not PSI subject to the attribution rules.'}); return; }
  }
  const {path, outcome} = walk(flow);
  let h = '';
  path.forEach(id => {
    const n = FLOWS[flow].nodes[id]; const a = S.answers[flow][id];
    h += `<div class="node ${a!==undefined?'answered':''}">
      <div class="ref">${esc(n.ref)}</div><div class="q">${n.q}</div>
      ${n.hint?`<div class="hint">${n.hint}</div>`:''}
      <div class="yn">
        <button data-flow="${flow}" data-node="${id}" data-val="1" class="${a===true?'sel-yes':''}">Yes</button>
        <button data-flow="${flow}" data-node="${id}" data-val="0" class="${a===false?'sel-no':''}">No</button>
      </div></div>`;
  });
  if (outcome) h += outcomeHTML(OUTCOMES[outcome]);
  el.innerHTML = h;
}
function outcomeHTML(o){ return `<div class="outcome ${o.tone}"><b>${esc(o.title)}</b>${esc(o.text)}</div>`; }

/* =========================================================
   GATEWAYS
========================================================= */
/* Each item: t = the indicator, h = what it looks like in practice */
const GW1 = [
  {t:'The arrangement is more complex than it needs to be to achieve its commercial purpose',
   h:'e.g. several trusts, companies or assignments layered together where a simpler structure would produce the same business result.'},
  {t:'The arrangement has no real purpose other than getting a tax advantage',
   h:'Take away the tax saving and there is no business reason left for setting it up this way.'},
  {t:'The tax result doesn\'t match the commercial or economic result',
   h:'e.g. the IPP does the work and effectively controls the income, but most of the profit is taxed to others at lower rates.'},
  {t:'Little or no risk is taken where significant risk would normally be expected',
   h:'e.g. an entity receives a large profit share without contributing capital, bearing business risk or taking on liability.'},
  {t:'It operates on non-commercial or non-arm\'s-length terms',
   h:'e.g. related parties are paid amounts, or deal on terms, that unrelated parties wouldn\'t accept.'},
  {t:'The legal form doesn\'t match what actually happens in substance',
   h:'e.g. an interest is legally assigned to a spouse or trust, but the IPP still controls it and effectively receives the benefit.'}
];
const GW2 = [
  {t:'Financing arrangements relating to non-arm\'s-length transactions',
   h:'Borrowing or funding between the firm, the IPP and associates that is not on commercial terms (e.g. related-party loans funding distributions or a buy-in).'},
  {t:'Exploits differences between accounting standards and tax law',
   h:'e.g. profit is recognised differently for accounts and tax so income ends up taxed in a lower-taxed entity, later, or not at all.'},
  {t:'Materially different from a standard Everett assignment or Galland partnership',
   h:'Goes beyond the accepted forms of assigning part of a partnership interest to an associate, e.g. unusual conditions, rights or pricing.'},
  {t:'Multiple classes of shares or units',
   h:'e.g. dividend access shares or special units that let profits be streamed to chosen family members or entities.'},
  {t:'Multiple assignments or disposals of the same equity interest',
   h:'The interest has been assigned, sold or re-assigned several times, e.g. to reset or re-direct entitlements.'},
  {t:'Misuse of the superannuation system',
   h:'e.g. part of a partnership interest assigned to an associated SMSF so firm profits are taxed at 15%.'},
  {t:'Income distributed to entities (other than the IPP) that have losses',
   h:'Profits sent to an entity with current-year or carried-forward losses so they are sheltered from tax.'}
];

function renderGateways(){
  const mk = (list, key) => list.map((g,i)=>`<label class="check"><input type="checkbox" data-gw="${key}" data-i="${i}" ${S[key][i]?'checked':''}> <span>${esc(g.t)}<span class="gwhint">${esc(g.h)}</span></span></label>`).join('');
  $('#gw1').innerHTML = mk(GW1,'gw1'); $('#gw2').innerHTML = mk(GW2,'gw2');
  renderGwResult();
}
function gatewayStatus(){
  const need = pcgNeeded();
  if (need !== true) return {pass:true, f1:[], f2:[], na:true};   // 3b not shown: ticks are ignored
  const f1 = GW1.filter((_,i)=>S.gw1[i]).map(g=>g.t); const f2 = GW2.filter((_,i)=>S.gw2[i]).map(g=>g.t);
  return {pass: !f1.length && !f2.length, f1, f2};
}
function renderGwResult(){
  const g = gatewayStatus();
  $('#gwResult').innerHTML = g.pass
    ? outcomeHTML({tone:'green', title:'Both gateways passed', text:'Nothing ticked, so the arrangement can be rated using the PCG 2021/4 risk scoring in 3c.'})
    : outcomeHTML({tone:'red', title:`Failed ${[g.f1.length?'Gateway 1':'', g.f2.length?'Gateway 2':''].filter(Boolean).join(' and ')}`,
        text:`${g.f1.length+g.f2.length} indicator(s) ticked. The arrangement can't be rated under the PCG 2021/4 risk scoring, so the score in 3c can't be relied on. The ATO may review it under Part IVA or other integrity rules regardless of the score.`});
}

/* =========================================================
   TAX + PCG 2021/4 SCORING
========================================================= */
function indTax(x, R){
  let t = 0; const b = R.ind;
  for (let i=0;i<b.length;i++){
    const lo=b[i][0], hi = i+1<b.length ? b[i+1][0] : Infinity;
    if (x > lo) t += (Math.min(x,hi)-lo)*b[i][1];
  }
  return t;
}
const TYPES = {
  ind:{label:'Individual (e.g. spouse, adult child)', individual:true},
  coBase:{label:'Company (e.g. bucket company) – base rate'},
  coFull:{label:'Company (e.g. bucket company) – full rate'},
  top:{label:'Trust – trustee assessed (s99A top rate)'},
  smsf:{label:'Super fund / SMSF (15%)'},
  custom:{label:'Other – custom rate'}
};
function rateFor(type, R, custom){
  if (type==='coBase') return R.coBase; if (type==='coFull') return R.coFull;
  if (type==='top') return R.top; if (type==='smsf') return .15;
  if (type==='custom') return num(custom)/100; return 0;
}

/* Net (cash) dividend -> franking credit and grossed-up amount.
   fr = { rate: company tax rate for franking, pct: franking % as 0–1 } */
function grossUp(div, fr){
  const d = num(div);
  const fc = fr.rate < 1 ? d * fr.rate / (1 - fr.rate) * fr.pct : 0;
  return {d, fc, gross: d + fc};
}

/* Tax on an individual's income FROM THE COMPANY (wages, super, dividends).
   Income tax is the extra tax caused by the company income on top of their other income,
   less franking credits (can be negative = refund). Medicare levy and offsets excluded. */
function personTax(p, R, o, fr){
  const wages = num(p.wages), sup = num(p.super), other = num(p.other);
  const dv = grossUp(p.div, fr);
  const assess = wages + dv.gross;
  const income = indTax(other + assess, R) - indTax(other, R);
  const afterFc = income - dv.fc;
  const contrib = o.contribTax ? sup * R.superTax : 0;
  let d293 = 0;
  if (o.div293 && sup > 0){
    const excess = Math.max(0, other + assess + sup - R.div293Threshold);
    d293 = .15 * Math.min(sup, excess);
  }
  return {wages, sup, div:dv.d, fc:dv.fc, gross:dv.gross, income, afterFc, contrib, d293,
          tax: afterFc + contrib + d293, share: wages + sup + dv.d};   // share = cash received (Factor 1)
}

/* Tax on a dividend received by a company, trust or super fund shareholder */
function entityTax(p, R, fr){
  const dv = grossUp(p.div, fr), rate = rateFor(p.type, R, p.rate);
  let tax = dv.gross * rate - dv.fc;
  if (p.type !== 'smsf') tax = Math.max(0, tax);   // excess franking credits refundable only to individuals & super funds
  return {div:dv.d, fc:dv.fc, gross:dv.gross, rate, tax, share:dv.d};
}

function f1Score(p){ if(p>90)return 1; if(p>75)return 2; if(p>60)return 3; if(p>=50)return 4; if(p>25)return 5; return 6; }
function f2Score(p){ if(p>40)return 1; if(p>35)return 2; if(p>=30)return 3; if(p>25)return 4; if(p>20)return 5; return 6; }
function f3Score(p){ if(p>200)return 1; if(p>150)return 2; if(p>100)return 3; if(p>90)return 4; if(p>70)return 5; return 6; }
function zoneFor(total, n){
  if (n===2) return total<=7?'green':total===8?'amber':'red';
  return total<=10?'green':total<=12?'amber':'red';
}
const r4 = x => Math.round(x*10000)/10000;

/* PCG 2021/4 for a company with one IPP.
   Profit entitlement (E) = company net profit before tax
                          + wages & super paid to the IPP and related parties (added back).
   Where the profit ends up (Factor 1), in cash terms as per the accounts:
       wages + super + cash dividends for each person, company tax,
       and the after-tax profit retained in the company. Franking credits are NOT used here.
   Where the tax is paid (Factor 2): company tax + each person's tax after franking credits. */
function compute(fin, fy){
  const R = RATES[fy] || RATES[DEFAULT_FY]; const o = fin.opts;
  const r = fin.coRate === 'coFull' ? R.coFull : R.coBase;
  const fr = {rate:r, pct: Math.min(100, Math.max(0, num(fin.franking))) / 100};
  const profit = num(fin.coProfit);
  const coTax = Math.max(0, profit) * r;

  const ipp = personTax(fin.ipp, R, o, fr);
  const people = [{name: S.client.ipp || 'Principal (IPP)', kind:'IPP', isIpp:true, ind:true, d:ipp}];
  fin.parties.forEach(p => {
    const ind = !!TYPES[p.type]?.individual;
    people.push({id:p.id, name: p.name || (ind ? 'Related individual' : 'Related entity'), kind: TYPES[p.type].label, ind,
                 d: ind ? personTax(p, R, o, fr) : entityTax(p, R, fr)});
  });

  const ippWagesSuper = ipp.wages + ipp.sup;
  const relWagesSuper = people.filter(x => x.ind && !x.isIpp).reduce((a, x) => a + x.d.wages + x.d.sup, 0);
  const E = profit + ippWagesSuper + relWagesSuper;
  const grossDivs = people.reduce((a, x) => a + x.d.gross, 0);
  const netDivs = people.reduce((a, x) => a + x.d.div, 0);
  const afterTaxProfit = Math.max(0, profit) - coTax;
  const retained = afterTaxProfit - netDivs;             // after tax; negative = paid from prior-year profits
  const priorYear = Math.max(0, -retained);
  const personalTax = people.reduce((a, x) => a + x.d.tax, 0);
  const totalTax = coTax + personalTax;

  const denom = E;
  const ippReturned = ipp.wages + ipp.div + (o.superInF1 ? ipp.sup : 0);
  const f1 = denom > 0 ? r4(ippReturned / denom * 100) : 0;
  const f2 = denom > 0 ? r4(totalTax / denom * 100) : 0;
  const bench = num(fin.benchmark);
  const useF3 = o.useF3 && bench > 0;
  const f3 = useF3 ? r4(ippReturned / bench * 100) : null;
  const s1 = f1Score(f1), s2 = f2Score(f2), s3 = useF3 ? f3Score(f3) : null;
  const n = useF3 ? 3 : 2; const total = s1 + s2 + (s3 || 0);
  const auto = f1 >= 100;
  const zone = denom <= 0 ? null : (auto ? 'green' : zoneFor(total, n));
  return {R, r, fr, profit, coTax, people, ipp, ippWagesSuper, relWagesSuper, E, grossDivs, netDivs, retained,
          afterTaxProfit, priorYear, personalTax, totalTax, denom, ippReturned, f1, f2, f3, s1, s2, s3, n, total, auto, zone};
}

/* Path to green: pay more of the profit to the IPP as dividends — taken from related-party
   dividends first-in-proportion and from this year's retained profits — until green. */
function pathToGreen(){
  const base = compute(S.fin, S.client.fy);
  if (!base.zone || base.zone === 'green') return null;
  const partyNet = S.fin.parties.reduce((a, p) => a + num(p.div), 0);
  const retainedNet = Math.max(0, base.retained);   // after-tax profit still in the company, available as dividends
  const movable = partyNet + retainedNet;
  if (movable <= 0) return {none:true};
  const step = Math.max(50, movable / 400);
  for (let s = step; ; s += step){
    s = Math.min(s, movable);
    const f = JSON.parse(JSON.stringify(S.fin));
    const k = s / movable;
    f.parties.forEach(p => { p.div = num(p.div) * (1 - k); });
    f.ipp.div = num(f.ipp.div) + s;
    const res = compute(f, S.client.fy);
    if (res.zone === 'green') return {shift:s, res, extraTax: res.totalTax - base.totalTax};
    if (s >= movable) break;
  }
  return {notReachable:true};
}

/* =========================================================
   RENDER: parties, tax lines, results
========================================================= */
function partyHTML(p){
  const ind = TYPES[p.type]?.individual;
  const opts = Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${p.type===k?'selected':''}>${v.label}</option>`).join('');
  const v = k => p[k] ? Number(num(p[k])).toLocaleString('en-AU') : '';
  return `<div class="party" data-pid="${p.id}">
    <div class="ph"><b>${esc(p.name||'Related party')}</b><button class="btn small danger" data-del="${p.id}">Remove</button></div>
    <div class="grid">
      <label class="f">Name<input type="text" data-p="name" value="${esc(p.name)}" placeholder="e.g. Spouse / Bucket Co"></label>
      <label class="f">Relationship<input type="text" data-p="rel" value="${esc(p.rel)}" placeholder="e.g. spouse, adult child"></label>
      <label class="f">Type<select data-p="type">${opts}</select></label>
      ${p.type==='custom'?`<label class="f">Tax rate (%)<input type="text" class="money" data-p="rate" value="${esc(p.rate)}" inputmode="decimal"></label>`:''}
    </div>
    <div class="grid" style="margin-top:8px">
      ${ind?`<label class="f">Wages paid by the company ($)<input type="text" class="money" data-p="wages" value="${v('wages')}" inputmode="decimal" placeholder="0"></label>
      <label class="f">Super paid by the company ($)<input type="text" class="money" data-p="super" value="${v('super')}" inputmode="decimal" placeholder="0"></label>`:''}
      <label class="f">Dividend received – net cash ($)<input type="text" class="money" data-p="div" value="${v('div')}" inputmode="decimal" placeholder="0"></label>
      ${ind?`<label class="f">Other taxable income, not from the company ($)<input type="text" class="money" data-p="other" value="${v('other')}" inputmode="decimal" placeholder="0"></label>`:''}
    </div>
    ${ind?`<label class="f" style="margin-top:8px">Services performed / hours (for reasonableness)<input type="text" data-p="duties" value="${esc(p.duties||'')}" placeholder="e.g. bookkeeping 6 hrs/week, admin"></label>`:''}
    <div class="taxline" data-taxline="${p.id}"></div>
  </div>`;
}
function renderParties(){
  $('#parties').innerHTML = S.fin.parties.length ? S.fin.parties.map(partyHTML).join('') : '<p class="muted" style="font-size:13px">No related parties added. Add a spouse or family member on the payroll, or a shareholder such as a bucket company.</p>';
}
const refundOr = n => n < 0 ? `${money(-n)} refund` : money(n);
function taxBreak(d){
  if (d.income === undefined){   // entity shareholder
    if (!d.div) return 'No dividend entered.';
    return `Dividend ${money(d.div)} + franking credits ${money(d.fc)} = <strong>${money(d.gross)}</strong> × ${(d.rate*100).toFixed(1)}% less franking credits → tax <strong>${refundOr(d.tax)}</strong>`;
  }
  const parts = [];
  if (d.wages) parts.push(`wages ${money(d.wages)}`);
  if (d.div) parts.push(`dividend ${money(d.div)} + franking credits ${money(d.fc)}`);
  if (!parts.length && !d.sup) return 'Nothing entered from the company.';
  let s = '';
  if (parts.length) s += `${parts.join(' + ')} → income tax <strong>${money(d.income)}</strong>${d.fc?` less franking credits ${money(d.fc)}`:''} = <strong>${refundOr(d.afterFc)}</strong>`;
  if (d.sup) s += `${s?' · ':''}super ${money(d.sup)} → contributions tax <strong>${money(d.contrib)}</strong>`;
  if (d.d293) s += ` · Div 293 <strong>${money(d.d293)}</strong>`;
  s += ` · <b>Total ${refundOr(d.tax)}</b>`;
  return s;
}
function renderResults(){
  const c = compute(S.fin, S.client.fy);
  $('#ippTax').innerHTML = taxBreak(c.ipp);
  c.people.forEach(x => {
    if (!x.id) return; const el = document.querySelector(`#psi-tool [data-taxline="${x.id}"]`);
    if (el) el.innerHTML = taxBreak(x.d);
  });
  $('#benchWrap').style.display = S.fin.opts.useF3 ? '' : 'none';
  $('#coNote').innerHTML = S.client.structure === 'company' ? '' :
    `<div class="warn">3C is set up for a company. The structure in Step 1 is set to ${esc({sole:'sole trader',trust:'trust',partnership:'partnership'}[S.client.structure])}, so treat these results with care.</div>`;

  // Profit entitlement build-up (shown under the inputs)
  $('#buildup').innerHTML = `<table class="t">
      <tr><td>Company net profit before tax</td><td class="n">${money(c.profit)}</td></tr>
      <tr><td>+ Salary &amp; super paid to the IPP</td><td class="n">${money(c.ippWagesSuper)}</td></tr>
      <tr><td>+ Wages &amp; super paid to related parties</td><td class="n">${money(c.relWagesSuper)}</td></tr>
      <tr class="sum"><td>= IPP's total profit entitlement</td><td class="n">${money(c.E)}</td></tr>
      <tr><td class="muted">Company tax at ${(c.r*100).toFixed(1)}% · after-tax profit this year</td><td class="n muted">${money(c.coTax)} · ${money(c.afterTaxProfit)}</td></tr>
      <tr><td class="muted">Dividends declared (cash) · retained after tax</td><td class="n muted">${money(c.netDivs)} · ${money(c.retained)}</td></tr>
    </table>`;

  let h = `<h2>PCG 2021/4 result</h2>`;
  if (c.denom <= 0){ $('#resultsCard').innerHTML = h + '<div class="info">Enter the company profit and amounts paid to calculate the score.</div>'; renderSidebar(); return; }
  if (c.priorYear > 1) h += `<div class="warn">Dividends of ${money(c.netDivs)} are ${money(c.priorYear)} more than this year's after-tax profit (${money(c.afterTaxProfit)}), so part is being paid from prior-year retained profits. This lifts Factor 1 for this year only; consider whether it reflects the ongoing arrangement.</div>`;

  // Table 1: where the profit ends up
  const share = x => c.E ? pct(x / c.E * 100) : '–';
  h += `<h3>Where the profit ends up (Factor 1)</h3>
    <table class="t"><thead><tr><th>Recipient</th><th class="n">Wages &amp; super</th><th class="n">Dividends (cash)</th><th class="n">Total</th><th class="n">% of profit</th></tr></thead><tbody>`;
  c.people.forEach(x => {
    const ws = x.ind ? x.d.wages + x.d.sup : 0;
    h += `<tr${x.isIpp?' class="ipp"':''}><td>${esc(x.name)}<br><span class="muted" style="font-size:12px">${esc(x.kind)}</span></td><td class="n">${x.ind?money(ws):'–'}</td><td class="n">${money(x.d.div)}</td><td class="n">${money(x.d.share)}</td><td class="n">${share(x.d.share)}</td></tr>`;
  });
  h += `<tr><td>Company tax</td><td class="n">–</td><td class="n">–</td><td class="n">${money(c.coTax)}</td><td class="n">${share(c.coTax)}</td></tr>`;
  h += `<tr><td>${c.retained >= 0 ? 'Retained in the company (after tax, not yet paid out)' : 'Paid out of prior-year retained profits'}</td><td class="n">–</td><td class="n">–</td><td class="n">${money(c.retained)}</td><td class="n">${share(c.retained)}</td></tr>`;
  h += `</tbody><tfoot><tr><td colspan="3">Total profit entitlement</td><td class="n">${money(c.E)}</td><td class="n">100.00%</td></tr></tfoot></table>`;

  // Table 2: where the tax is paid
  h += `<h3>Where the tax is paid (Factor 2)</h3>
    <table class="t"><thead><tr><th>Taxpayer</th><th>Tax on</th><th class="n">Tax paid</th></tr></thead><tbody>
    <tr><td>Company</td><td class="muted">${money(c.profit)} net profit × ${(c.r*100).toFixed(1)}%</td><td class="n">${money(c.coTax)}</td></tr>`;
  c.people.forEach(x => {
    if (!x.d.share) return;
    const on = x.ind ? [x.d.wages?`wages ${money(x.d.wages)}`:'', x.d.gross?`dividends ${money(x.d.div)} (grossed-up ${money(x.d.gross)}, less franking credits)`:'', x.d.sup&&(S.fin.opts.contribTax||x.d.d293)?`super ${money(x.d.sup)}`:''].filter(Boolean).join(' · ')
                     : `dividend ${money(x.d.div)} (grossed-up ${money(x.d.gross)}, less franking credits)`;
    h += `<tr><td>${esc(x.name)}</td><td class="muted">${on}</td><td class="n">${refundOr(x.d.tax)}</td></tr>`;
  });
  h += `</tbody><tfoot><tr><td colspan="2">Total tax on the profit entitlement · effective tax rate ${pct(c.f2)}</td><td class="n">${money(c.totalTax)}</td></tr></tfoot></table>`;

  h += `<h3>Scoring</h3><table class="t score-row"><thead><tr><th>Factor</th><th class="n">Result</th><th class="n">Score</th></tr></thead><tbody>
    <tr><td>1 · Profit entitlement returned to the IPP<br><span class="muted" style="font-size:12px">${money(c.ippReturned)} ÷ ${money(c.denom)}${S.fin.opts.superInF1?'':' (super excluded)'}</span></td><td class="n">${pct(c.f1)}</td><td class="n"><b>${c.s1}</b></td></tr>
    <tr><td>2 · Total effective tax rate<br><span class="muted" style="font-size:12px">${money(c.totalTax)} ÷ ${money(c.denom)}</span></td><td class="n">${pct(c.f2)}</td><td class="n"><b>${c.s2}</b></td></tr>
    <tr><td>3 · Remuneration vs commercial benchmark${c.f3!==null?`<br><span class="muted" style="font-size:12px">${money(c.ippReturned)} ÷ ${money(num(S.fin.benchmark))}</span>`:''}</td><td class="n">${c.f3!==null?pct(c.f3):'Not assessed'}</td><td class="n"><b>${c.s3??'–'}</b></td></tr>
  </tbody><tfoot><tr><td>Aggregate (${c.n} factors · green ≤ ${c.n===2?7:10}, amber ${c.n===2?'8':'11–12'}, red ≥ ${c.n===2?9:13})</td><td></td><td class="n">${c.total}</td></tr></tfoot></table>`;

  const gw = gatewayStatus();
  const lbl = {green:'Low risk',amber:'Moderate risk',red:'High risk'}[c.zone];
  h += `<div class="traffic" style="margin-top:14px">
    <div class="lights"><i class="red ${c.zone==='red'?'on':''}"></i><i class="amber ${c.zone==='amber'?'on':''}"></i><i class="green ${c.zone==='green'?'on':''}"></i></div>
    <div><div class="small">PCG 2021/4 risk zone</div><div class="big">${c.zone.toUpperCase()} · ${lbl}</div>
    <div class="small">${c.auto?'The IPP receives 100% of the profit entitlement – automatically green.':`Score ${c.total} on ${c.n} factors.`}${gw.pass?'':' ⚠ Gateway failed – score cannot be relied on.'}</div></div></div>`;

  const p = pathToGreen();
  if (p){
    if (p.none) h += `<div class="info">There are no related-party dividends or retained profits to redirect. To move toward green, consider increasing the IPP's salary.</div>`;
    else if (p.notReachable) h += `<div class="info">Paying all related-party dividends and this year's retained profits to the IPP still doesn't reach green. Review related-party wages and super, and Factor 3.</div>`;
    else h += `<div class="info"><b>Path to green:</b> paying about <b>${money(p.shift)}</b> more in dividends (net cash) to the IPP, taken from related-party dividends and this year's retained profits, gives Factor 1 of ${pct(p.res.f1)}, an effective tax rate of ${pct(p.res.f2)} and a score of ${p.res.total} (green). Additional tax ≈ <b>${money(p.extraTax)}</b>.</div>`;
  }
  $('#resultsCard').innerHTML = h;
  renderSidebar();
}

/* =========================================================
   SIDEBAR / DOTS / SUMMARY
========================================================= */
function toneOf(o){ return o ? (OUTCOMES[o]?.tone || 'grey') : ''; }
function renderSidebar(){
  const psi = flowOutcome('psi'), psb = flowOutcome('psb'), iva = walk('iva').outcome;
  const c = compute(S.fin, S.client.fy); const gw = gatewayStatus(); const need = pcgNeeded();
  const pill = (tone, txt) => tone ? `<span class="pill ${tone}">${esc(txt)}</span>` : '<span class="muted">Pending</span>';
  $('#sidebar').innerHTML = `
    <div class="stat"><span>PSI</span>${pill(toneOf(psi), psi?OUTCOMES[psi].title:'')}</div>
    <div class="stat"><span>PSB</span>${psb==='SKIP'?pill('grey','Not required'):pill(toneOf(psb), psb?OUTCOMES[psb].title:'')}</div>
    <div class="stat"><span>Part IVA check</span>${pill(toneOf(iva), iva?OUTCOMES[iva].title:'')}</div>
    <div class="stat"><span>Gateways</span>${need===false ? pill('grey','Not required') : need===null ? '<span class="muted">Pending</span>' : pill(gw.pass?'green':'red', gw.pass?'Passed':'Failed')}</div>
    <div class="stat"><span>PCG 2021/4</span>${c.zone?pill(c.zone, c.zone.toUpperCase()+' · '+c.total):'<span class="muted">Pending</span>'}</div>
    ${c.denom>0?`<div class="stat"><span>Factor 1 / ETR</span><span>${pct(c.f1)} / ${pct(c.f2)}</span></div>`:''}
    <div class="stat"><span>Tax year</span><span>${esc(RATES[S.client.fy]?.label||S.client.fy)}</span></div>`;
  const setDot = (i,t) => { const d=$('#dot'+i); d.className='dot '+(t||''); };
  setDot(1, toneOf(psi)); setDot(2, psb==='SKIP'?'grey':toneOf(psb));
  const tones = [toneOf(iva), c.zone, gw.pass ? '' : 'red'];
  const step3 = tones.includes('red') ? 'red' : tones.includes('amber') ? 'amber' : toneOf(iva);
  setDot(3, step3); setDot(4, step3);
}

function recommendations(){
  const out = [];
  const psi = flowOutcome('psi'), psb = flowOutcome('psb'), iva = walk('iva').outcome;
  const c = compute(S.fin, S.client.fy); const gw = gatewayStatus(); const st = S.client.structure;
  if (psb==='PSI_APPLIES' && st!=='sole') out.push('PSI rules apply: attribute net PSI to the principal worker (s86-15). Check entity deductions against Div 85 / s86-60, and consider paying the principal salary within 14 days of year end to reduce the attributed amount.');
  if (psb==='PSI_APPLIES' && S.fin.parties.some(p=>TYPES[p.type]?.individual && num(p.wages)>0)) out.push('Related-party wages are only deductible to the entity if they are for principal work (s86-60). Non-principal work (e.g. admin) paid to associates is not deductible.');
  if (psb==='PSI_APPLIES' && st==='sole') out.push('Sole trader not a PSB: deductions limited by Div 85 (e.g. no deductions for rent/mortgage interest on the home, or payments to associates for non-principal work). Report PSI in the PSI section of the return.');
  if (psb==='DETERMINATION') out.push('Prepare a PSB determination application. Document why the tests would be met (or the special circumstances). Treat the income as PSI until the determination is issued.');
  if (psb==='PSB') out.push('Retain evidence supporting the PSB test passed (contracts for results, advertising, contractor invoices, premises lease) and complete the PSI section of the entity return.');
  if (iva==='IVA_MAY') out.push('Part IVA indicators present: discuss increasing remuneration to the principal, paying out retained profits in the following year, or reducing splitting to associates.');
  if (S.fin.parties.some(p=>TYPES[p.type]?.individual && (num(p.wages)>0 || num(p.super)>0))) out.push('Document the services performed, hours and market rate for each related individual receiving wages/super to support "reasonable remuneration for bona fide services".');
  if (!gw.pass) out.push('One or more PCG 2021/4 gateway indicators are present — the risk score cannot be relied on. Consider restructuring or a private ruling.');
  if (S.fin.parties.some(p=>p.type==='smsf')) out.push('Income is flowing to a super fund/SMSF — this is a listed high-risk feature. Review under the non-arm\'s-length income rules as well as PCG 2021/4.');
  if (c.denom>0 && c.retained>1) out.push(`${money(c.retained)} of this year's after-tax profit is retained in the company. It counts against Factor 1 until paid to the IPP; record the expected timing of future dividends.`);
  if (c.priorYear>1) out.push(`Dividends include about ${money(c.priorYear)} paid from prior-year retained profits. Note this in the file, as it lifts Factor 1 for this year only.`);
  if (c.denom>0 && S.fin.parties.some(p=>!TYPES[p.type]?.individual && num(p.div)>0)) out.push('Dividends are paid to a company or trust shareholder. Check for Division 7A loans or unpaid present entitlements that effectively return funds to the IPP or associates.');
  if (c.zone==='amber' || c.zone==='red'){
    const p = pathToGreen();
    out.push(`PCG 2021/4 rating is ${c.zone.toUpperCase()}. Expect ATO analysis of the arrangement.` + (p && p.shift ? ` Redirecting ≈ ${money(p.shift)} to the IPP would reach green at an extra tax cost of ≈ ${money(p.extraTax)}.` : ''));
  }
  if (S.fin.opts.useF3===false && c.denom>0) out.push('Factor 3 not assessed. Record why a commercial remuneration benchmark was impractical to determine.');
  if (!out.length) out.push('No specific issues flagged. Keep workpapers supporting each answer.');
  return out;
}

function renderSummary(){
  const psi = flowOutcome('psi'), psb = flowOutcome('psb'), ivaW = walk('iva');
  const c = compute(S.fin, S.client.fy); const gw = gatewayStatus();
  const oBox = (label, o) => `<h3>${label}</h3>` + (o ? outcomeHTML(OUTCOMES[o]) : '<div class="info">Not yet completed.</div>');
  let h = `<h2>Summary – ${esc(S.client.name||'Client')}${S.client.ipp?` (${esc(S.client.ipp)})`:''}</h2>
    <p class="lead">${esc(RATES[S.client.fy]?.label||'')} · Structure: ${esc({sole:'Sole trader',company:'Company',trust:'Trust',partnership:'Partnership'}[S.client.structure])}</p>`;
  h += oBox('1 · PSI', psi);
  h += psb==='SKIP' ? '<h3>2 · PSB</h3>'+outcomeHTML({tone:'grey',title:'Not required',text:'Income is not PSI subject to the attribution rules.'}) : oBox('2 · PSB', psb);
  h += oBox('3a · Part IVA structure check', ivaW.outcome);
  if (pcgNeeded() === false) h += `<h3>3b · Gateways</h3>` + outcomeHTML({tone:'grey', title:'Not required', text:'The Part IVA structure check did not indicate Part IVA may apply.'});
  else h += `<h3>3b · Gateways</h3>` + (gw.pass ? outcomeHTML({tone:'green',title:'Passed',text:'No lack-of-rationale or high-risk indicators ticked.'}) : outcomeHTML({tone:'red',title:'Failed',text:[...gw.f1,...gw.f2].join('; ')}));
  if (c.zone) h += `<h3>3c · PCG 2021/4</h3>` + outcomeHTML({tone:c.zone, title:`${c.zone.toUpperCase()} zone – score ${c.total} (${c.n} factors)`, text:`Factor 1: ${pct(c.f1)} (score ${c.s1}) · Factor 2 ETR: ${pct(c.f2)} (score ${c.s2}) · Factor 3: ${c.f3!==null?pct(c.f3)+' (score '+c.s3+')':'not assessed'}`});
  h += `<h3>Recommendations</h3><ul class="recs">${recommendations().map(r=>`<li>${esc(r)}</li>`).join('')}</ul>`;
  $('#summaryCard').innerHTML = h;
}

function fileNote(){
  const psi = flowOutcome('psi'), psb = flowOutcome('psb');
  const c = compute(S.fin, S.client.fy); const gw = gatewayStatus();
  const L = [];
  const trail = flow => walk(flow).path.map(id=>{ const n=FLOWS[flow].nodes[id]; const a=S.answers[flow][id]; return `  - ${n.q.replace(/<[^>]+>/g,'')} [${n.ref}] → ${a===undefined?'unanswered':a?'Yes':'No'}`; });
  L.push('FILE NOTE – PSI / PSB / PART IVA ASSESSMENT');
  L.push(`Client: ${S.client.name||'-'}    Principal worker (IPP): ${S.client.ipp||'-'}`);
  L.push(`Structure: ${S.client.structure}    Income year: ${RATES[S.client.fy]?.label||S.client.fy}`);
  L.push(`Prepared: ${new Date().toLocaleDateString('en-AU')}`);
  L.push('');
  L.push('1. PERSONAL SERVICES INCOME (Div 84)'); L.push(...trail('psi')); L.push(`  Conclusion: ${psi?OUTCOMES[psi].title:'Incomplete'}`); L.push('');
  L.push('2. PERSONAL SERVICES BUSINESS (Div 87)');
  if (psb==='SKIP') L.push('  Not required.'); else { L.push(...trail('psb')); L.push(`  Conclusion: ${psb?OUTCOMES[psb].title:'Incomplete'}`); }
  L.push('');
  const iv = walk('iva');
  L.push('3a. PART IVA – STRUCTURE CHECK'); L.push(...trail('iva')); L.push(`  Conclusion: ${iv.outcome?OUTCOMES[iv.outcome].title:'Incomplete'}`); L.push('');
  L.push('3b. PCG 2021/4 GATEWAYS');
  if (pcgNeeded() === false) L.push('  Not required – the Part IVA structure check did not indicate Part IVA may apply.');
  else L.push(gw.pass?'  Both gateways passed – no indicators identified.':'  FAILED – indicators: '+[...gw.f1,...gw.f2].join('; ')); L.push('');
  L.push('3c. PCG 2021/4 RISK ASSESSMENT (company, one IPP)');
  if (c.denom>0){
    L.push(`  Company net profit before tax: ${money(c.profit)}`);
    L.push(`  Add back salary & super to the IPP: ${money(c.ippWagesSuper)}`);
    L.push(`  Add back wages & super to related parties: ${money(c.relWagesSuper)}`);
    L.push(`  IPP's total profit entitlement: ${money(c.E)}`);
    L.push(`  Dividends declared (cash): ${money(c.netDivs)}, franked ${Math.round(c.fr.pct*100)}% at ${(c.r*100).toFixed(1)}% (franking credits used for personal tax only, not Factor 1)`);
    if (c.priorYear>1) L.push(`  Note: ${money(c.priorYear)} of dividends paid from prior-year retained profits.`);
    L.push('  Where the profit ends up:');
    c.people.forEach(x=>{ if (x.d.share) L.push(`   - ${x.name} (${x.kind}): ${money(x.d.share)} (${pct(x.d.share/c.E*100)})${x.d.div?` incl. cash dividends ${money(x.d.div)}`:''}`); });
    L.push(`   - Company tax: ${money(c.coTax)} (${pct(c.coTax/c.E*100)})`);
    L.push(`   - ${c.retained>=0?'Retained in company (after tax)':'Paid from prior-year retained profits'}: ${money(c.retained)} (${pct(c.retained/c.E*100)})`);
    L.push('  Where the tax is paid:');
    L.push(`   - Company tax: ${money(c.coTax)}`);
    c.people.forEach(x=>{ if (x.d.share) L.push(`   - ${x.name}: ${refundOr(x.d.tax)} (after franking credits)`); });
    L.push(`  Total tax: ${money(c.totalTax)}`);
    L.push(`  Factor 1 – returned to IPP: ${pct(c.f1)} → score ${c.s1}`);
    L.push(`  Factor 2 – effective tax rate: ${pct(c.f2)} → score ${c.s2}`);
    L.push(`  Factor 3 – vs benchmark: ${c.f3!==null?pct(c.f3)+' → score '+c.s3:'not assessed'}`);
    L.push(`  Aggregate: ${c.total} on ${c.n} factors → ${c.zone.toUpperCase()} ZONE${c.auto?' (100% returned to IPP)':''}`);
    const rel = S.fin.parties.filter(p=>TYPES[p.type]?.individual && p.duties);
    if (rel.length){ L.push('  Related-party services:'); rel.forEach(p=>L.push(`   - ${p.name||'Related individual'} (${p.rel||'associate'}): ${p.duties}`)); }
  } else L.push('  Not completed.');
  L.push('');
  L.push('RECOMMENDATIONS'); recommendations().forEach((r,i)=>L.push(`  ${i+1}. ${r}`));
  L.push(''); L.push('Note: tax calculated excluding Medicare levy and offsets, consistent with the PCG 2021/4 effective tax rate method.');
  $('#fileNote').value = L.join('\n');
}

/* =========================================================
   GLOBAL RENDER + EVENTS
========================================================= */
function renderAll(){
  $('#clientName').value = S.client.name; $('#ippName').value = S.client.ipp;
  $('#structure').value = S.client.structure; $('#fy').value = S.client.fy;
  $$('[data-fin]').forEach(el=>{ const k=el.dataset.fin; const v=S.fin[k]; el.value = el.tagName==='SELECT' ? v : (v? Number(v).toLocaleString('en-AU'):''); });
  $$('[data-ipp]').forEach(el=>{ const v=S.fin.ipp[el.dataset.ipp]; el.value = v? Number(v).toLocaleString('en-AU'):''; });
  $$('[data-opt]').forEach(el=> el.checked = !!S.fin.opts[el.dataset.opt]);
  renderFlow('psi'); renderFlow('psb'); renderFlow('iva');
  renderIvaStage(); renderGateways(); renderParties(); renderResults(); renderSummary(); fileNote();
}
function refreshFlows(){ renderFlow('psi'); renderFlow('psb'); renderFlow('iva'); renderIvaStage(); renderSidebar(); renderSummary(); }

/* 3b (gateways) is only needed when the 3a structure check concludes Part IVA may apply.
   3c (risk scoring) always shows. Returns true (needed), false (not needed) or null (3a unfinished). */
function pcgNeeded(){
  const o = walk('iva').outcome;
  return o ? o === 'IVA_MAY' : null;
}
function renderIvaStage(){
  const need = pcgNeeded(), o = walk('iva').outcome;
  $('#ivaDeep').style.display = need ? '' : 'none';
  $('#ivaSkip').innerHTML = need ? '' : need === null
    ? '<div class="card"><div class="info" style="margin:0">Complete the Part IVA structure check (3a) above. The PCG 2021/4 gateways (3b) will appear here if Part IVA may apply.</div></div>'
    : '<div class="card">' + outcomeHTML({tone:'grey', title:'3b not required',
        text:`The structure check concluded: ${OUTCOMES[o].title}. The PCG 2021/4 gateways only need to be completed where Part IVA may apply.`}) + '</div>';
}

$('#fy').innerHTML = Object.entries(RATES).map(([k,v])=>`<option value="${k}">${esc(v.label||k)}</option>`).join('');

document.getElementById('psi-tool').addEventListener('click', e=>{
  const t = e.target;
  if (t.dataset.flow){ S.answers[t.dataset.flow][t.dataset.node] = t.dataset.val==='1'; refreshFlows(); fileNote(); return; }
  const stepBtn = t.closest('[data-step]') || t.closest('[data-go]');
  if (stepBtn){ goStep(stepBtn.dataset.step || stepBtn.dataset.go); return; }
  if (t.dataset.del){ S.fin.parties = S.fin.parties.filter(p=>String(p.id)!==t.dataset.del); renderParties(); renderResults(); renderSummary(); fileNote(); return; }
});
function goStep(n){
  $$('nav.steps button').forEach(b=>b.classList.toggle('active', b.dataset.step===String(n)));
  $$('.panel').forEach(p=>p.classList.toggle('active', p.dataset.panel===String(n)));
  if (n==='4'||n===4){ renderSummary(); fileNote(); }
  window.scrollTo({top:0,behavior:'smooth'});
}
document.getElementById('psi-tool').addEventListener('input', e=>{
  const t = e.target;
  if (t.id==='clientName'){ S.client.name=t.value; }
  else if (t.id==='ippName'){ S.client.ipp=t.value; renderResults(); }
  else if (t.dataset.fin && t.tagName!=='SELECT'){ S.fin[t.dataset.fin]=num(t.value); renderResults(); }
  else if (t.dataset.ipp){ S.fin.ipp[t.dataset.ipp]=num(t.value); renderResults(); }
  else if (t.dataset.p && t.tagName!=='SELECT'){
    const pid = t.closest('.party').dataset.pid; const p = S.fin.parties.find(x=>String(x.id)===pid);
    const k = t.dataset.p; p[k] = ['name','rel','duties'].includes(k) ? t.value : num(t.value);
    if (k==='name') t.closest('.party').querySelector('.ph b').textContent = t.value||'Related party';
    renderResults();
  }
});
document.getElementById('psi-tool').addEventListener('change', e=>{
  const t = e.target;
  if (t.id==='structure'){ S.client.structure=t.value; refreshFlows(); }
  else if (t.id==='fy'){ S.client.fy=t.value; renderResults(); }
  else if (t.dataset.fin && t.tagName==='SELECT'){ S.fin[t.dataset.fin]=t.value; renderResults(); }
  else if (t.dataset.opt){ S.fin.opts[t.dataset.opt]=t.checked; renderResults(); }
  else if (t.dataset.gw){ S[t.dataset.gw][t.dataset.i]=t.checked; renderGwResult(); renderResults(); }
  else if (t.dataset.p==='type'){ const pid=t.closest('.party').dataset.pid; S.fin.parties.find(x=>String(x.id)===pid).type=t.value; renderParties(); renderResults(); }
  else if (t.id==='fileIn' && t.files[0]){
    const r = new FileReader(); r.onload = ()=>{ try{ S = Object.assign(blankState(), JSON.parse(r.result)); uid = Math.max(1,...S.fin.parties.map(p=>p.id+1)); renderAll(); }catch(err){ alert('Could not read that file.'); } }; r.readAsText(t.files[0]); t.value='';
  }
  renderSummary(); fileNote();
});
document.getElementById('psi-tool').addEventListener('focusout', e=>{
  const t = e.target;
  if (t.classList && t.classList.contains('money') && t.value){ const n=num(t.value); t.value = t.dataset.p==='rate' ? n : n.toLocaleString('en-AU'); }
});
$('#addParty').onclick = ()=>{ S.fin.parties.push({id:uid++, name:'', rel:'', type:'ind', wages:0, super:0, div:0, other:0, rate:0, duties:''}); renderParties(); renderResults(); };
$('#btnReset').onclick = ()=>{ if(confirm('Clear all inputs?')){ S = blankState(); renderAll(); goStep(1);} };
$('#btnExport').onclick = ()=>{
  const blob = new Blob([JSON.stringify(S,null,2)],{type:'application/json'});
  const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
  a.download = `PSI-assessment-${(S.client.name||'client').replace(/[^a-z0-9]+/gi,'-')}.json`; a.click();
};
$('#btnImport').onclick = ()=> $('#fileIn').click();
$('#btnCopy').onclick = ()=>{ const ta=$('#fileNote'); ta.select(); navigator.clipboard?.writeText(ta.value).catch(()=>document.execCommand('copy')); $('#btnCopy').textContent='Copied ✓'; setTimeout(()=>$('#btnCopy').textContent='Copy file note',1500); };
$('#btnRegen').onclick = fileNote;

// Register with the suite: build the page once everything has loaded
registerTab('psi', {
  init(){ renderAll(); }
});
})();
